=== eddygarcas/qt-beta-projects/KPersonalAsistant/vcc/SettingsManager/ViewsSettings.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="viewssettings">
		<xs:annotation>
			<xs:documentation>
				Comment describing your root element
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="setting">
					<xs:complexType>
						<xs:all>
							<xs:element name="objectname"
								type="xs:string" />
							<xs:element name="label" type="xs:integer" />
							<xs:element name="title" type="xs:integer" />
							<xs:element name="type" type="xs:string" />
							<xs:element name="options">
								<xs:complexType>
									<xs:sequence
										maxOccurs="unbounded">
										<xs:element name="option">
											<xs:complexType>
												<xs:all>
													<xs:element
														name="label" type="xs:string" />
													<xs:element
														name="value" type="xs:string" />
												</xs:all>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:all>
						<xs:attribute name="id" type="xs:string"
							use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== eddygarcas/qt-beta-projects/KPersonalAsistant/vcc/SettingsManager/ViewsSettings.xml
<?xml version="1.0" encoding="UTF-8"?>
<viewssettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="ViewsSettings.xsd">
  <setting id="1">
    <objectname>ID-TEST-COM</objectname>
    <label>1</label>
    <title>21</title>
    <type>CDSINT8CONTINUOUS</type>
    <options/>
  </setting>
  <setting id="2">
    <objectname>DEF-EVNT</objectname>
    <label>134</label>
    <title>22</title>
    <type>CDSINT8DISCRETE</type>
    <options>
      <option>
        <label>324</label>
        <value>232</value>
      </option>
    </options>
  </setting>
  <setting id="3">
    <objectname>ID-DOS-COM</objectname>
    <label>3</label>
    <title>23</title>
    <type>CDSINT8CONTINUOUS</type>
    <options/>
  </setting>
  <setting id="4">
    <objectname>SETTINGS-MANAGER-COM</objectname>
    <label>4</label>
    <title>24</title>
    <type>CDSINT32DISCRETE</type>
    <options>
      <option>
        <label>4562</label>
        <value>274</value>
      </option>
      <option>
        <label>456</label>
        <value>563</value>
      </option>
    </options>
  </setting>
  <setting id="5">
    <objectname>INK-SUPPLY-COM</objectname>
    <label>5</label>
    <title>25</title>
    <type>CDSINT8CONTINUOUS</type>
    <options/>
  </setting>
  <setting id="6">
    <objectname>MEDIA-NAME-COM</objectname>
    <label>6</label>
    <title>26</title>
    <type>CDSINT8CONTINUOUS</type>
    <options/>
  </setting>
  <setting id="7">
    <objectname>PAPER-COLOR-COM</objectname>
    <label>7</label>
    <title>27</title>
    <type>CDSSTRING</type>
    <options/>
    <characters>
      <char>a</char>
      <char>b</char>
    </characters>
  </setting>
  <setting id="8">
    <objectname>PAPER-COLOR-COM</objectname>
    <label>7</label>
    <title>27</title>
    <type>CDSRANGECONTINUOUS</type>
    <range>
      <min>1</min>
      <max>10</max>
    </range>
    <options/>
  </setting>
</viewssetings>
